dist: release
release:
  github:
    owner: ekristen
    name: cast
  extra_files:
    - glob: "./*.pub"
env:
  - CGO_ENABLED=0
builds:
  - id: cast
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
archives:
  - id: cast
    builds:
      - cast
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        format: zip
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all
nfpms:
  - id: cast
    package_name: cast
    builds:
      - cast
    vendor: ekristen.dev
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}"
    homepage: https://github.com/ekristen/cast
    maintainer: Erik Kristensen <erik@erikkristensen.com>
    description: Cast is an installer tool for any Cast compatible distro
    license: MIT
    formats:
      - deb
    deb:
      signature:
        key_file: "{{ .Env.NFPM_GPG_KEY }}"
        type: origin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
